// File generated by FlutterFire CLI.
// This is a placeholder - run `flutterfire configure` to generate the real config.
//
// To regenerate, run: `flutterfire configure --project=your-project-id`

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run `flutterfire configure` to generate firebase_options.dart',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoRQob_raU_EhTgAQundvPw_8T4n_4bbY',
    appId: '1:986562521840:web:15c1ca03678f6182483035',
    messagingSenderId: '986562521840',
    projectId: 'pontaj-app-7735a',
    authDomain: 'pontaj-app-7735a.firebaseapp.com',
    storageBucket: 'pontaj-app-7735a.firebasestorage.app',
    measurementId: 'G-EV1R3RH644',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-34EO3GZvXtHRPFR1j8AbBMl9CWwHGX4',
    appId: '1:986562521840:android:1c5256eb32dbf58f483035',
    messagingSenderId: '986562521840',
    projectId: 'pontaj-app-7735a',
    storageBucket: 'pontaj-app-7735a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVAoTWAzqVqIHH23SMI587yHY4eN7EQp0',
    appId: '1:986562521840:ios:cfbd114e958d5ad1483035',
    messagingSenderId: '986562521840',
    projectId: 'pontaj-app-7735a',
    storageBucket: 'pontaj-app-7735a.firebasestorage.app',
    iosClientId:
        '986562521840-o6seltd1r3686m3ssla8muvbo3puc84h.apps.googleusercontent.com',
    iosBundleId: 'com.pontajpro.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVAoTWAzqVqIHH23SMI587yHY4eN7EQp0',
    appId: '1:986562521840:ios:cfbd114e958d5ad1483035',
    messagingSenderId: '986562521840',
    projectId: 'pontaj-app-7735a',
    storageBucket: 'pontaj-app-7735a.firebasestorage.app',
    iosClientId:
        '986562521840-o6seltd1r3686m3ssla8muvbo3puc84h.apps.googleusercontent.com',
    iosBundleId: 'com.pontajpro.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoRQob_raU_EhTgAQundvPw_8T4n_4bbY',
    appId: '1:986562521840:web:92d3acb526068b14483035',
    messagingSenderId: '986562521840',
    projectId: 'pontaj-app-7735a',
    authDomain: 'pontaj-app-7735a.firebaseapp.com',
    storageBucket: 'pontaj-app-7735a.firebasestorage.app',
    measurementId: 'G-Q32DX3V0WW',
  );
}
